# IMPORT DATASET
crime-data-los-angeles.csv : This dataset reflects incidents of crime in the City of Los Angeles dating back to 2020. This data is transcribed from original crime reports that are typed on paper and therefore there may be some inaccuracies within the data.

the steps are as follows :
- import library
- read and load dataset
- display 5 last rows

In [27]:
# import library
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
from google.colab import sheets
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
# read and load dataset
df = pd.read_csv('/content/drive/MyDrive/Course/Datasets/crime-data-los-angeles.csv')
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130

In [29]:
# display 5 last rows
df.tail()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1004842,240710284,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,NaN,34.0362,-118.3284
1004843,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460
1004844,240410786,10/14/2024 12:00:00 AM,10/11/2024 12:00:00 AM,2330,4,Hollenbeck,421,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,NaN,34.0675,-118.2240
1004845,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868
1004846,240910892,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,NaN,34.1961,-118.4510

# EXPLORATORY DATASET
the steps are as follows :
- display info type data columns
- summary statistics dataset
- checking for missing values
- checking for duplicates

In [30]:
# display info type data columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004847 entries, 0 to 1004846
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004847 non-null  int64
 1   Date Rptd       1004847 non-null  object
 2   DATE OCC        1004847 non-null  object
 3   TIME OCC        1004847 non-null  int64
 4   AREA            1004847 non-null  int64
 5   AREA NAME       1004847 non-null  object
 6   Rpt Dist No     1004847 non-null  int64
 7   Part 1-2        1004847 non-null  int64
 8   Crm Cd          1004847 non-null  int64
 9   Crm Cd Desc     1004847 non-null  object
 10  Mocodes         853256 non-null   object
 11  Vict Age        1004847 non-null  int64
 12  Vict Sex        860243 non-null   object
 13  Vict Descent    860231 non-null   object
 14  Premis Cd       1004831 non-null  float64
 15  Premis Desc     1004259 non-null  object
 16  Weapon Used Cd  327193 non-null   float64
 17  Weapon Desc     327193 non-null   object
 18  Status          1004846 non-null  object
 19  Status Desc     1004847 non-null  object
 20  Crm Cd 1        1004836 non-null  float64
 21  Crm Cd 2        69130 non-null    float64
 22  Crm Cd 3        2315 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1004847 non-null  object
 25  Cross Street    154221 non-null   object
 26  LAT             1004847 non-null  float64
 27  LON             1004847 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 214.7+ MB

In [31]:
# summary statistics dataset
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004831e+06,327193.000000,1.004836e+06,69130.000000,2315.000000,64.00000,1.004847e+06,1.004847e+06
mean,2.202171e+08,1.339911e+03,1.069147e+01,1.115607e+03,1.400307e+00,5.001353e+02,2.891905e+01,3.056073e+02,363.944543,4.998958e+02,958.115941,984.022030,991.21875,3.399820e+01,-1.180908e+02
std,1.318835e+07,6.510691e+02,6.110286e+00,6.111622e+02,4.899607e-01,2.052622e+02,2.199224e+01,2.192915e+02,123.741225,2.050627e+02,110.359911,52.340476,27.06985,1.610827e+00,5.582785e+00
min,8.170000e+02,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,1.100000e+02,-4.000000e+00,1.010000e+02,101.000000,1.100000e+02,210.000000,310.000000,821.00000,0.000000e+00,-1.186676e+02
25%,2.106168e+08,9.000000e+02,5.000000e+00,5.870000e+02,1.000000e+00,3.310000e+02,0.000000e+00,1.010000e+02,311.000000,3.310000e+02,998.000000,998.000000,998.00000,3.401470e+01,-1.184305e+02
50%,2.209158e+08,1.420000e+03,1.100000e+01,1.139000e+03,1.000000e+00,4.420000e+02,3.000000e+01,2.030000e+02,400.000000,4.420000e+02,998.000000,998.000000,998.00000,3.405890e+01,-1.183225e+02
75%,2.311101e+08,1.900000e+03,1.600000e+01,1.613000e+03,2.000000e+00,6.260000e+02,4.400000e+01,5.010000e+02,400.000000,6.260000e+02,998.000000,998.000000,998.00000,3.416490e+01,-1.182739e+02
max,2.521040e+08,2.359000e+03,2.100000e+01,2.199000e+03,2.000000e+00,9.560000e+02,1.200000e+02,9.760000e+02,516.000000,9.560000e+02,999.000000,999.000000,999.00000,3.433430e+01,0.000000e+00

In [32]:
# checking for missing values
df.isnull().sum()

DR_NO                   0
Date Rptd               0
DATE OCC                0
TIME OCC                0
AREA                    0
AREA NAME               0
Rpt Dist No             0
Part 1-2                0
Crm Cd                  0
Crm Cd Desc             0
Mocodes            151591
Vict Age                0
Vict Sex           144604
Vict Descent       144616
Premis Cd              16
Premis Desc           588
Weapon Used Cd     677654
Weapon Desc        677654
Status                  1
Status Desc             0
Crm Cd 1               11
Crm Cd 2           935717
Crm Cd 3          1002532
Crm Cd 4          1004783
LOCATION                0
Cross Street       850626
LAT                     0
LON                     0
dtype: int64

In [33]:
# checking for duplicates
duplicates = df.duplicated().sum()
print("\nNumber of duplicates in the dataset:")
print(duplicates)

Number of duplicates in the dataset:
0

# CLEANING DATASET
the steps are as follows :
- rename variable
- replace and columns missing values
- checking for missing values again
- dropping duplicates
- checking for duplicates again

In [34]:
# rename variable
df = df.rename(columns={'DR_NO': 'number_id',
                        'Date Rptd': 'date_rptd',
                        'DATE OCC' : 'date_occ',
                        'TIME OCC' : 'time_occ',
                        'AREA': 'area_number',
                        'AREA NAME': 'area_name',
                        'Rpt Dist No' : 'rpt_dist_no',
                        'Part 1-2' : 'part_1/2',
                        'Crm Cd' : 'crime_cd',
                        'Crm Cd Desc': 'crime_cd_desc',
                        'Mocodes' : 'mocodes',
                        'Vict Age' : 'vict_age',
                        'Vict Sex': 'vict_sex',
                        'Vict Descent': 'vict_descent',
                        'Premis Cd' : 'premis_cd',
                        'Premis Desc' : 'premis_desc',
                        'Weapon Used Cd': 'weapon_used_cd',
                        'Weapon Desc': 'weapon_desc',
                        'Status' : 'status',
                        'Status Desc' : 'status_desc',
                        'Crm Cd 1' : 'crime_cd_1',
                        'Crm Cd 2' : 'crime_cd_2',
                        'Crm Cd 3' : 'crime_cd_3',
                        'Crm Cd 4' : 'crime_cd_4',
                        'LOCATION' : 'location',
                        'Cross Street': 'cross_street',
                        'LAT' : 'lat',
                        'LON' : 'lon'})
df.head()

,number_id,date_rptd,date_occ,time_occ,area_number,area_name,rpt_dist_no,part_1/2,crime_cd,crime_cd_desc,...,status,status_desc,crime_cd_1,crime_cd_2,crime_cd_3,crime_cd_4,location,cross_street,lat,lon
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130

In [35]:
# replace and columns missing values
df['mocodes'].fillna(df['mocodes'].mode()[0], inplace=True)
df['vict_sex'].fillna(df['vict_sex'].mode()[0], inplace=True)
df['vict_descent'].fillna(df['vict_descent'].mode()[0], inplace=True)
df['premis_cd'].fillna(df['premis_cd'].median(), inplace=True)
df['premis_desc'].fillna(df['premis_desc'].mode()[0], inplace=True)
df['weapon_used_cd'].fillna(df['weapon_used_cd'].median(), inplace=True)
df['weapon_desc'].fillna(df['weapon_desc'].mode()[0], inplace=True)
df['status'].fillna(df['status'].mode()[0], inplace=True)
df['cross_street'].fillna(df['cross_street'].mode()[0], inplace=True)
df.drop(columns=['crime_cd_1'], inplace=True)
df.drop(columns=['crime_cd_2'], inplace=True)
df.drop(columns=['crime_cd_3'], inplace=True)
df.drop(columns=['crime_cd_4'], inplace=True)

<ipython-input-35-91c7f8c34964>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mocodes'].fillna(df['mocodes'].mode()[0], inplace=True)
<ipython-input-35-91c7f8c34964>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['vict_sex'].fillna(df['vict_sex'].mode()[0], inplace=True)
<ipython-input-35-91c7f8c34964>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['vict_descent'].fillna(df['vict_descent'].mode()[0], inplace=True)
<ipython-input-35-91c7f8c34964>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['premis_cd'].fillna(df['premis_cd'].median(), inplace=True)
<ipython-input-35-91c7f8c34964>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['premis_desc'].fillna(df['premis_desc'].mode()[0], inplace=True)
<ipython-input-35-91c7f8c34964>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weapon_used_cd'].fillna(df['weapon_used_cd'].median(), inplace=True)
<ipython-input-35-91c7f8c34964>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weapon_desc'].fillna(df['weapon_desc'].mode()[0], inplace=True)
<ipython-input-35-91c7f8c34964>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['status'].fillna(df['status'].mode()[0], inplace=True)
<ipython-input-35-91c7f8c34964>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cross_street'].fillna(df['cross_street'].mode()[0], inplace=True)

In [36]:
# checking for missing values again
missing_values_after = df.isnull().sum()
print("\nMissing values in the dataset after handling:")
print(missing_values_after)

Missing values in the dataset after handling:
number_id         0
date_rptd         0
date_occ          0
time_occ          0
area_number       0
area_name         0
rpt_dist_no       0
part_1/2          0
crime_cd          0
crime_cd_desc     0
mocodes           0
vict_age          0
vict_sex          0
vict_descent      0
premis_cd         0
premis_desc       0
weapon_used_cd    0
weapon_desc       0
status            0
status_desc       0
location          0
cross_street      0
lat               0
lon               0
dtype: int64

In [37]:
# dropping duplicates
df.drop_duplicates(inplace=True)

In [38]:
# checking for duplicates again
duplicates_after = df.duplicated().sum()
print("\nNumber of duplicates in the dataset after removing duplicates:")
print(duplicates_after)

Number of duplicates in the dataset after removing duplicates:
0

In [39]:
# displaying the first rows dataset
df.head()

,number_id,date_rptd,date_occ,time_occ,area_number,area_name,rpt_dist_no,part_1/2,crime_cd,crime_cd_desc,...,premis_cd,premis_desc,weapon_used_cd,weapon_desc,status,status_desc,location,cross_street,lat,lon
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,101.0,STREET,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,1900 S LONGWOOD AV,BROADWAY,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,128.0,BUS STOP/LAYOVER (ALSO QUERY 124),400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,1000 S FLOWER ST,BROADWAY,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,1400 W 37TH ST,BROADWAY,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,405.0,CLOTHING STORE,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,14000 RIVERSIDE DR,BROADWAY,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,101.0,STREET,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,200 E AVENUE 28,BROADWAY,34.0820,-118.2130

In [20]:
# summary statistics dataset
print("\nSummary statistics of the dataset:")
df.describe()

Summary statistics of the dataset:

,number_id,time_occ,area_number,rpt_dist_no,part_1/2,crime_cd,vict_age,premis_cd,weapon_used_cd,lat,lon
count,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06,1.004847e+06
mean,2.202171e+08,1.339911e+03,1.069147e+01,1.115607e+03,1.400307e+00,5.001353e+02,2.891905e+01,3.056057e+02,3.882598e+02,3.399820e+01,-1.180908e+02
std,1.318835e+07,6.510691e+02,6.110286e+00,6.111622e+02,4.899607e-01,2.052622e+02,2.199224e+01,2.192901e+02,7.260326e+01,1.610827e+00,5.582785e+00
min,8.170000e+02,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,1.100000e+02,-4.000000e+00,1.010000e+02,1.010000e+02,0.000000e+00,-1.186676e+02
25%,2.106168e+08,9.000000e+02,5.000000e+00,5.870000e+02,1.000000e+00,3.310000e+02,0.000000e+00,1.010000e+02,4.000000e+02,3.401470e+01,-1.184305e+02
50%,2.209158e+08,1.420000e+03,1.100000e+01,1.139000e+03,1.000000e+00,4.420000e+02,3.000000e+01,2.030000e+02,4.000000e+02,3.405890e+01,-1.183225e+02
75%,2.311101e+08,1.900000e+03,1.600000e+01,1.613000e+03,2.000000e+00,6.260000e+02,4.400000e+01,5.010000e+02,4.000000e+02,3.416490e+01,-1.182739e+02
max,2.521040e+08,2.359000e+03,2.100000e+01,2.199000e+03,2.000000e+00,9.560000e+02,1.200000e+02,9.760000e+02,5.160000e+02,3.433430e+01,0.000000e+00

In [40]:
# display info type data columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004847 entries, 0 to 1004846
Data columns (total 24 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   number_id       1004847 non-null  int64
 1   date_rptd       1004847 non-null  object
 2   date_occ        1004847 non-null  object
 3   time_occ        1004847 non-null  int64
 4   area_number     1004847 non-null  int64
 5   area_name       1004847 non-null  object
 6   rpt_dist_no     1004847 non-null  int64
 7   part_1/2        1004847 non-null  int64
 8   crime_cd        1004847 non-null  int64
 9   crime_cd_desc   1004847 non-null  object
 10  mocodes         1004847 non-null  object
 11  vict_age        1004847 non-null  int64
 12  vict_sex        1004847 non-null  object
 13  vict_descent    1004847 non-null  object
 14  premis_cd       1004847 non-null  float64
 15  premis_desc     1004847 non-null  object
 16  weapon_used_cd  1004847 non-null  float64
 17  weapon_desc     1004847 non-null  object
 18  status          1004847 non-null  object
 19  status_desc     1004847 non-null  object
 20  location        1004847 non-null  object
 21  cross_street    1004847 non-null  object
 22  lat             1004847 non-null  float64
 23  lon             1004847 non-null  float64
dtypes: float64(4), int64(7), object(13)
memory usage: 184.0+ MB

In [41]:
# load to csv
df.to_csv("crime-data-los-angeles-cleaning.csv", index=False)